# Generated by Django 3.0.3 on 2020-02-14 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khmap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='locLat',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=10),
        ),
        migrations.AddField(
            model_name='content',
            name='locLng',
            field=models.DecimalField(decimal_places=7, default=None, max_digits=10),
        ),
    ]
