# Generated by Django 3.0.3 on 2020-02-14 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khmap', '0003_auto_20200214_2138'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='locLat',
            field=models.DecimalField(decimal_places=17, default=None, max_digits=20),
        ),
        migrations.AlterField(
            model_name='content',
            name='locLng',
            field=models.DecimalField(decimal_places=17, default=None, max_digits=20),
        ),
    ]
