# Generated by Django 3.0.3 on 2020-02-17 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('khmap', '0004_auto_20200214_2142'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='locLat',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=12),
        ),
        migrations.AlterField(
            model_name='content',
            name='locLng',
            field=models.DecimalField(decimal_places=9, default=None, max_digits=12),
        ),
    ]
